config/routes.rb
# frozen_string_literal: true

#
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # devise_for :admin
  devise_for :users,
             controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'home#index'
  get  'catalog',            to: 'books#index'
  get  'settings/addresses', to: 'addresses#index'
  post 'settings/addresses', to: 'addresses#create'
  put  'settings/addresses', to: 'addresses#update'
  get  'settings/privacy',   to: 'users#edit'

  resources :books, only: %i[index show update] do
    resources :reviews, only: :create
  end

  resource  :cart, only: %i[show update]
  resources :checkout
  resources :credit_card
  resources :orders, only: %i[index show]
  resources :order_items, only: %i[create update destroy]
  resource :admin

  resource :user, only: %i[edit] do
    collection do
      patch 'update_email'
      patch 'update_password'
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

# User
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :omniauthable, omniauth_providers: [:facebook]

  attr_accessor :skip_password_validation

  validates :email, presence: true,
                    format: { with: /@/, message: 'ivalid format' }

  validates :password,
            format: { with: /\A\S(?=.*\d)(?=.*[a-z])(?=.*[A-Z])\S*\z/i },
                      # message: 'should contain at least 1 uppercase, at least \
                     # 1 lowercase, at least 1 number and not contain spaces.' },
            unless: :skip_password_validation

  has_many :orders, dependent: :destroy
  has_many :order_items, through: :orders, dependent: :destroy
  has_many :books, through: :order_items, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :addresses, dependent: :destroy

  has_one :billing, dependent: :destroy
  has_one :shipping, dependent: :destroy
  has_one :credit_card, dependent: :destroy

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name
      user.avatar = auth.info.image
      user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session['devise.facebook_data'] && session['devise.facebook_data']['extra']['raw_info']
        user.email = data['email'] if user.email.blank?
      end
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

#
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

#
class UsersController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!

  def edit
    @user = current_user
  end

  def update_email
    @user = current_user
    @user.skip_password_validation = true
    @user.skip_confirmation!
    @user.skip_reconfirmation!
    if @user.update_without_password(user_params)
      bypass_sign_in(@user)
      flash[:success] = 'Email successfuly changed'
      redirect_to settings_privacy_path
    else
      flash[:danger] = @user.errors.full_messages.to_sentence
      render :edit
    end
  end

  def update_password
    @user = current_user
    if @user.update_with_password(user_params)
      bypass_sign_in(@user)
      flash[:success] = 'Password successfuly changed'
      redirect_to settings_privacy_path
    else
      flash[:danger] = @user.errors.full_messages.to_sentence
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :current_password, :password, :password_confirmation, :avatar)
  end
end

app/views/users/_edit_email.haml
%p.in-gold-500.font-18.mb-25= t('settings.e-mail')
= form_for(@user, url: { action: "update_email" }, html: {class: 'general-form-md email' }) do |f|
  .form-group.mb-35
    = f.label :email, t('settings.enter_e-mail'), class: 'control-label input-label'
    = f.email_field :email, autofocus: true, autocomplete: "off", class: 'form-control', value: current_user.email
  .general-text-align
    = f.submit t('settings.save'), class: 'btn btn-default mb-35'

app/views/users/_edit_password.haml
%p.in-gold-500.font-18.mb-25= t('settings.password')
= form_for(@user, url: { action: "update_password" }, html: { class: 'general-form-md divider-lg-bottom pb-25'}) do |f|
  .form-group.mb-30
    = f.label :current_password, t('settings.old_password'), class: "control-label input-label"
    = f.password_field :current_password, class: "form-control", autocomplete: "off", placeholder: t('settings.old_password')
  .form-group.mb-30
    = f.label :password, t('settings.new_password'), class: "control-label input-label"
    = f.password_field :password, class: "form-control", autofocus: true, autocomplete: "off", t('settings.new_password')
  .form-group.mb-40
    = f.label :password_confirmation, t('settings.confirm_password'), class: "control-label input-label"
    = f.password_field :password_confirmation, autocomplete: "off", class: "form-control", placeholder: t('settings.confirm_password')
  .general-text-align
    = f.submit t('settings.save'), class: 'btn btn-default mb-10'

app/views/users/_remove_account.haml
%p.in-gold-500.font-18.mb-25= t('settings.remove_account')
.general-settings-btn
  = button_to t('settings.remove_account'), registration_path(@user), class: 'btn btn-default mb-20', data: { confirm: "Are you sure?" }, method: :delete
.form-group.checkbox.general-settings-checkbox
  %label.checkbox-label#remove_account
    %input.checkbox-input{type: "checkbox", hidden: "true"}
    %span.checkbox-icon
      %i.fa.fa-check
    %span.checkbox-text= t('settings.im_agree_lost_all_data')

app/views/users/edit.html.haml
%main.container
  %h1.general-title-margin= t('settings.settings')
  %ul.nav.clearfix.mb-20{role: "tablist"}
    %li.tab-item{role: "presentation"}
      = link_to t('settings.address'), settings_addresses_path, class: 'tab-link'
    %li.tab-item{role: "presentation"}
      = link_to t('settings.privacy'), settings_privacy_path, class: 'tab-link filter-link active'
  .tab-content
    .row.mb-60
      .col-sm-5
        = render 'users/edit_email'
      .col-sm-5.col-sm-offset-1
        = render 'users/edit_password'
      .col-sm-12
        = render 'users/remove_account'