config/routes.rb
# frozen_string_literal: true

#
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # devise_for :admin
  devise_for :users,
             controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'home#index'
  get  'catalog',            to: 'books#index'
  get  'settings/addresses', to: 'addresses#index'
  post 'settings/addresses', to: 'addresses#create'
  put  'settings/addresses', to: 'addresses#update'
  get  'settings/privacy',   to: 'users#edit'

  resources :books, only: %i[index show update] do
    resources :reviews, only: :create
  end

  resource  :cart, only: %i[show update]
  resources :checkout
  resources :credit_card
  resources :orders, only: %i[index show]
  resources :order_items, only: %i[create update destroy]
  resource :admin

  resource :user, only: %i[edit] do
    collection do
      patch 'update_email'
      patch 'update_password'
    end
  end
end

app/models/order.rb
# frozen_string_literal: true

#
class Order < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :delivery, optional: true
  belongs_to :coupon, optional: true
  belongs_to :credit_card, optional: true

  has_many :order_items, dependent: :destroy
  has_many :books, through: :order_items, dependent: :destroy

  has_many :addresses, dependent: :destroy
  has_one :billing, dependent: :destroy
  has_one :shipping, dependent: :destroy

  after_create :set_number_and_status

  enum status: %i[in_progress in_queue in_delivery delivered canceled]

  scope :in_progress, -> { where status: %w[in_progress in_queue in_delivery] }
  scope :payed,  -> { where.not status: %w[in_progress canceled] }
  scope :placed, -> { where.not(status: %w[in_progress]).order('created_at desc') }

  def place_in_queue
    update(status: 1, completed_at: Time.current)
  end

  def sub_total
    order_items.to_a.sum(&:total)
  end

  def total
    coupon_discount = coupon ? coupon.discount : 0.00
    delivery_price = delivery ? delivery.price : 0.00

    sub_total - coupon_discount + delivery_price
  end

  private

  def set_number_and_status
    update(number: "R#{id.to_s.rjust(8, '0')}", status: 0)
  end
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

#
class OrdersController < ApplicationController
  before_action :authenticate_user!

  ORDER_FILTERS = { in_queue: 'Waiting for processing',
                    in_delivery: 'In delivery',
                    delivered: 'Delivered',
                    canceled: 'Canceled',
                    all: 'All' }.freeze

  def index
    order_status = params[:order_status]

    @orders = case order_status
              when 'in_queue' then current_user.orders.in_queue
              when 'in_delivery' then current_user.orders.in_delivery
              when 'delivered' then current_user.orders.delivered
              when 'canceled' then current_user.orders.canceled
              else current_user.orders.placed
              end

    @active_filter = order_status ? ORDER_FILTERS[order_status.to_sym] : 'All'
  end

  def show
    @order = current_user.orders.find(params[:id])
  end
end

app/views/orders/index.html.haml
%main.container.general-main-wrap
  %h1.mt-0.mb-25= t('order.my_orders')
  %p.lead.small.mb-10.visible-xs= t('order.sort_by')
  .dropdowns.dropdown.general-order-dropdown
    %a.dropdown-toggle.lead.small{href: "#", 'data-toggle': "dropdown", role: "button", 'aria-haspopup': "true", 'aria-expanded': "false"}
      = @active_filter
      %i.fa.fa-angle-down.dropdown-icon.pull-right
    %ul.dropdown-menu
      %li
        = link_to t('order.status.all'), orders_path(order_status: 'all')
      %li
        = link_to t('order.status.in_queue'), orders_path(order_status: 'in_queue')
      %li
        = link_to t('order.status.in_delivery'), orders_path(order_status: 'in_delivery')
      %li
        = link_to t('order.status.delivered'), orders_path(order_status: 'delivered')
      %li
        = link_to t('order.status.canceled'), orders_path(order_status: 'canceled')
  .visible-xs
    - @orders.each do |order|
      .general-cart-item.divider-lg-bottom.pt-0
        %table.table
          %tr
            %td.col-half
              %span.in-grey-600= t('order.number')
            %td.col-half
              %span.general-order-number= order.number
          %tr
            %td
              %span.in-grey-600= t('order.complited_at')
            %td
              %span.in-grey-900.font-16.fw-300= order.completed_at.strftime("%Y-%m-%d")
          %tr
            %td
              %span.in-grey-600= t('order.statuss')
            %td
              %span.font-16.in-grey-900.fw-300= order.status.capitalize
          %tr
            %td
              %span.in-grey-600= t('order.total')
            %td
              %strong.font-16= number_to_euro order.total

  .hidden-xs.mb-res-50
    %table.table.table-hover
      %thead
        %tr
          %th
            %span.in-grey-600= t('order.number')
          %th
            %span.in-grey-600= t('order.complited_at')
          %th
            %span.in-grey-600= t('order.statuss')
          %th
            %span.in-grey-600= t('order.total')
      %tbody
        - @orders.each do |order|
          %tr
            %td
              = link_to order_path(order), class: "nav-link" do
                %span.general-order-number= order.number
            %td
              %span.in-grey-900.font-16.fw-300= order.completed_at.strftime("%Y-%m-%d")
            %td
              %span.font-16.in-grey-900.fw-300= order.status.capitalize
            %td
              %strong.font-16= number_to_euro order.total

app/views/orders/show.html.haml
%main.container.general-main-wrap
  %h1.general-title-margin= t('complete.order') + @order.number
  .row.mb-20
    .col-sm-3
      %h3.general-subtitle.mt-0= t('settings.shipping')
      %p.general-address
        = "#{@order.shipping.first_name} #{@order.shipping.last_name}"
        %br
        = @order.shipping.address
        %br
        = "#{@order.shipping.city} #{@order.shipping.zip}"
        %br
        = @order.shipping.country
        %br
        = "Phone #{@order.shipping.phone}"
    .col-sm-3
      %h3.general-subtitle.mt-0= t('settings.billing')
      %p.general-address
        = "#{@order.billing.first_name} #{@order.billing.last_name}"
        %br
        = @order.billing.address
        %br
        = "#{@order.billing.city} #{@order.billing.zip}"
        %br
        = @order.billing.country
        %br
        = "Phone #{@order.billing.phone}"
    .col-sm-3
      %h3.general-subtitle.mt-0= t('confirm.shipments')
      %p.general-address
        = @order.delivery.name
        %br
        = @order.delivery.time
    .col-sm-3
      %h3.general-subtitle.mt-0= t('confirm.payment_info')
      %p.general-address
        = "**** **** **** #{@order.credit_card.number.last(4)}"
        %br
        = @order.credit_card.month_year
  .visible-xs
    - @order.order_items.each do |order_item|
      .general-cart-item.divider-lg
        .general-img-wrap-table
          %img.cart-img-shadow{src: "http://jonathantweedy.com/resources/thumbs/SmashingBook5ResponsiveWebDesign.jpg", alt: "design-book"}
        %p.title= order_item.book.title
        %table.table
          %tr
            %td
              %span.in-grey-600= t('cart.price')
            %td
              %span.font-16.in-gold-500= number_to_euro order_item.book.price
          %tr
            %td.vertical-middle
              %span.in-grey-600= t('cart.quantity')
            %td
              %span= order_item.quantity
          %tr
            %td
              %span.in-grey-600= t('cart.subtotal')
            %td
              %span.font-16.in-gold-500= number_to_euro order_item.total

  .hidden-xs.divider-lg.pt-20
    %table.table.table-hover
      %thead
        %tr
          %th
            %span.in-grey-600= t('complete.book')
          %th.col-method
          %th
            %span.in-grey-600= t('cart.price')
          %th
            %span.in-grey-600= t('cart.quantity')
          %th
            %span.in-grey-600= t('complete.total')
      %tbody
        - @order.order_items.each do |order_item|
          %tr
            %td
              .general-img-wrap-table
                %img.cart-img-shadow.pull-left{src: "http://jonathantweedy.com/resources/thumbs/SmashingBook5ResponsiveWebDesign.jpg", alt: "design-book"}
            %td
              %p.title= order_item.book.title
              %p.in-grey-600.fw-300= order_item.book.description.split('.').first
            %td
              %span.font-16.in-gold-500= number_to_euro order_item.book.price
            %td
              %span.ml-30= order_item.quantity
            %td
              %span.font-16.in-gold-500= number_to_euro order_item.total

  .text-center.general-text-right
    %p.in-gold-500.font-18= t('cart.summary')
    %table.general-summary-table.general-summary-table-right.general-text-right
      = render 'checkout/order_summary', order: @order