config/routes.rb
# frozen_string_literal: true

#
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # devise_for :admin
  devise_for :users,
             controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'home#index'
  get  'catalog',            to: 'books#index'
  get  'settings/addresses', to: 'addresses#index'
  post 'settings/addresses', to: 'addresses#create'
  put  'settings/addresses', to: 'addresses#update'
  get  'settings/privacy',   to: 'users#edit'

  resources :books, only: %i[index show update] do
    resources :reviews, only: :create
  end

  resource  :cart, only: %i[show update]
  resources :checkout
  resources :credit_card
  resources :orders, only: %i[index show]
  resources :order_items, only: %i[create update destroy]
  resource :admin

  resource :user, only: %i[edit] do
    collection do
      patch 'update_email'
      patch 'update_password'
    end
  end
end

app/views/layouts/_flash_messages.html.haml
#flash-display
  .container
    - flash.each do |type, message|
      %div{:class => "alert alert-#{type == 'notice' ? 'info' : type} fadeout", 'data-dismiss': 'alert'}
        %button.close &times;
        = message

app/views/layouts/_footer.html.haml
%footer.navbar-inverse
  .container
    .row
      .col-sm-9
        %ul.list-inline.general-align.mb-25
          %li
            = link_to t('button.home'), root_path, class: "nav-link"
          %li
            %a.nav-link{href: "#"}= t('header.shop')
          - if user_signed_in?
            %li
              = link_to t('button.orders'), orders_path, class: "nav-link"
            %li
              = link_to t('button.settings'), settings_addresses_path, class: "nav-link"
      .col-sm-3
        %p.general-nav-mail support@bookstore.com
        %p.general-nav-number (555)-555-5555
        %ul.list-inline.general-align
          %li
            %a.nav-link{href: "#"}
              %i.fa.fa-facebook{'aria-hidden': "true"}
          %li
            %a.nav-link{href: "#"}
              %i.fa.fa-twitter{'aria-hidden': "true"}
          %li
            %a.nav-link{href: "#"}
              %i.fa.fa-google-plus{'aria-hidden': "true"}
          %li
            %a.nav-link{href: "#"}
              %i.fa.fa-instagram{'aria-hidden': "true"}

app/views/layouts/_header.html.haml
%header.navbar.navbar-default
  .container
    .navbar-header
      %button.navbar-toggle.pull-left{type: "button", 'data-toggle': "collapse", 'data-target': "#navbar"}
        %span.sr-only
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{href: root_path}= t('header.logo')
      %a.shop-link.pull-right.visible-xs{href: cart_path}
        = render 'layouts/shop_icon'
    %a.shop-link.pull-right.hidden-xs{href: cart_path}
      = render 'layouts/shop_icon'
    #navbar.navbar-collapse.collapse.pl-30{'aria-expanded': "false"}
      .visible-xs
        %button.close{type: "button", 'aria-label': "Close"}
          %span{'aria-hidden': "true"} &times;
        %ul.nav.navbar-nav
          %li
            = link_to t('button.home'), root_path
          %li
            %a{type: "button", 'data-toggle': "collapse", href: "#menu_shop", 'aria-expanded': "false", 'aria-controls': "menu_shop"}= t('header.shop')
            %ul#menu_shop.collapse.list-unstyled.pl-30.mb-10{'aria-expanded': "false"}
              - categories.each do |category|
                %li
                  = link_to "#{category.name}", catalog_path(category_id: category.id), class: "collapse-link"
          - if user_signed_in?
            %li
              %a{type: "button", 'data-toggle': "collapse", href: "#menu_my_account", 'aria-expanded': "false", 'aria-controls': "menu_my_account"}= t('button.my_account')
              %ul#menu_my_account.collapse.list-unstyled.pl-30.mb-10{'aria-expanded': "false"}
                %li
                  = link_to t('button.orders'), orders_path, class: "collapse-link"
                %li
                  = link_to t('button.settings'), settings_addresses_path, class: "collapse-link"
                %li
                  = link_to t('button.admin'), root_path, class: "collapse-link"
            %li
              = link_to t('button.log_out'), destroy_user_session_path, method: :delete
          - else
            %li
              = link_to t('button.log_in'), new_user_session_path
            %li
              = link_to t('button.sign_up'), new_user_registration_path
      .hidden-xs
        %ul.nav.navbar-nav
          %li
            = link_to t('button.home'), root_path
          %li.dropdown
            %a.dropdown-toggle{href: "#", 'data-toggle': "dropdown", role: "button", 'aria-haspopup': "true", 'aria-expanded': "false"}= t('header.shop')
            %ul.dropdown-menu
              - categories.each do |category|
                %li
                  = link_to "#{category.name}", catalog_path(category_id: category.id)
          - if user_signed_in?
            %li.dropdown
              %a.dropdown-toggle{href: "#", 'data-toggle': "dropdown", role: "button", 'aria-haspopup': "true", 'aria-expanded': "false"}= t('button.my_account')
              %ul.dropdown-menu
                %li
                  = link_to t('button.orders'), orders_path
                %li
                  = link_to t('button.settings'), settings_addresses_path
                - if current_user.admin?
                  %li
                    = link_to t('button.admin'), admin_path
                %li.divider{role: "separator"}
                %li
                  = link_to t('button.log_out'), destroy_user_session_path, method: :delete
          - else
            %li
              = link_to t('button.log_in'), new_user_session_path
            %li
              = link_to t('button.sign_up'), new_user_registration_path

app/views/layouts/_shop_icon.html.haml
- items_count = cart_items_count
- if items_count > 0
  %span.shop-icon
    %span.shop-quantity= items_count
- else
  %span.shop-icon

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "UTF-8"}/
    %meta{:content => "width=device-width", :name => "viewport"}/
    %title Bookstore
    = csrf_meta_tags
    = favicon_link_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/flash_messages'
    = render 'layouts/header'
    = yield
    = render 'layouts/footer'